//
//  KeyChallengeCollapsibleTableContentManager.swift
//  Citizen-Scientist-Project
//
//  Created by David Gonzalez on 4/18/18.
//  Copyright © 2018 Key Biscayne. All rights reserved.
//

import Foundation

class KeyChallengeCollapsibleTableContentManager {
    class func fetchContent() -> [KeyChallengeTableSection] {
        
        let tableSections: [KeyChallengeTableSection] = [
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "PRE K - 1ST", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "COLLAGE", subHeader: "(INDIVIDUALS, GROUPS, & CLASS | UP TO 2FT X 3FT)", bodyText: "Turn trash to treasure. Create a collage using found materials from a beach or mangrove clean-up. Use any non-perishable materials available. Please include a written description (by the teacher), which describes the process of creating the collage, the materials collected, and the lessons learned during the process on how trash affects the environment."),
                KeyChallengeTableRow(header: "2D DEPICTION OF HUMAN IMPACT*", subHeader: "(INDIVIDUALS & AT-HOME | UP TO 10IN X 14IN)", bodyText: "Create a 2-D depiction (painting, print screening, etc.) of a native Key Biscayne setting that includes some sort of effect caused to the environment by humans. Technique may include all types of paint and dry media (colored pencils, oil pastels, sharpies, etc.)"),
                KeyChallengeTableRow(header: "PHOTOGRAPH*", subHeader: "(INDIVIDUALS & AT-HOME | 8IN X 10IN WITHOUT MAT)", bodyText: "Take a photograph (micro or macro) of an element of the natural aquatic or shoreline environment of Key Biscayne (i.e. the beach, the mangroves, marine life, etc.) which also shows any kind of human impact (trash, invasive species, development, etc.). Include a title for the photograph as well as a short description of the location and circumstances of the photo." + "\n\n" + "Photographs must also be uploaded to the Key Science interactive map. Go to https://www.keyscience.org/lab/record/ and click on \"Upload your photos\""),
                KeyChallengeTableRow(header: "BOOK", subHeader: "(INDIVIDUALS, GROUPS, & CLASS | MAX 28 PGS INCLUDING COVER)", bodyText: "Create a book (for example ABC, Counting, Colors, a story, or any other idea) depicting or talking about the problem of pollution on Key Biscayne. The artwork and words must be student generated, but the book may be computer printed or assembled by the teacher for very young students. Include a description of the creation of the book and the students’ involvement. Please try to include elements of how humans (especially children) can positively impact the environment as it relates to the topic or theme of the book."),
                KeyChallengeTableRow(header: "SCIENCE PROJECT", subHeader: "(INDIVIDUALS, GROUPS, & CLASS | ON A PRESENTATION/SCIENCE BOARD)", bodyText: "Choose a local, native habitat (reef, shoreline, freshwater, etc.) and observe and list the different plants and animals present and how they are affected by humans in that habitat. Describe the habitat (Is it fresh or salt water? Does the water have a current? Is there sand, dirt, or plants?) and describe the different species that are there (Are they birds, fish, grass, trees, etc? Do the animals live there or are they visiting?). Have people made it easier or harder for animals to live in these habitats? Present data on a poster/foam core board with pictures."),
            ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "2ND - 3RD", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "COLLAGE", subHeader: "(INDIVIDUALS, GROUPS, & CLASS | UP TO 2FT X 3FT)", bodyText: "Turn trash to treasure. Create a collage using found materials from a beach or mangrove clean-up. Use any non-perishable materials available. Please include a written description (by the teacher), which describes the process of creating the collage, the materials collected, and the lessons learned during the process."),
                KeyChallengeTableRow(header: "2D DEPICTION OF HUMAN IMPACT*", subHeader: "(INDIVIDUALS & AT-HOME | UP TO 10IN X 14IN)", bodyText: "Create a 2-D depiction (painting, print screening, etc.) of a native Key Biscayne setting that includes some sort of an effect caused to the environment by humans or some way it has been impacted by humans. Technique may include all types of paint and dry media (colored pencils, oil pastels, sharpies, etc.)"),
                KeyChallengeTableRow(header: "NATIVE SPECIES DESCRIPTION", subHeader: "(INDIVIDUALS & GROUPS | UP TO 2FT X 3FT)", bodyText: "Choose a plant or animal that is native to Key Biscayne and create a poster with pictures and describe how it is impacted by humans."),
                KeyChallengeTableRow(header: "PHOTOGRAPH*", subHeader: "(INDIVIDUALS & AT-HOME | 8IN X 10IN WITHOUT MAT)", bodyText: "Take a photograph (macro or micro) of an element of the natural environment of Key Biscayne (i.e. the beach, the mangroves, marine life, etc.) which also shows something natural and manmade together. Include a title for the photograph as well as a short description of the location of the photo." + "\n\n" + "Photographs must also be uploaded to the Key Science interactive map. Go to https://www.keyscience.org/lab/record/ and click on \"Upload your photos\""),
                KeyChallengeTableRow(header: "SCIENCE PROJECT", subHeader: "(INDIVIDUALS & GROUPS | ON A PRESENTATION/SCIENCE BOARD)", bodyText: "Choose a local, native habitat (reef, shoreline, freshwater, etc.) and observe and list the different plants and animals present and how they are affected by humans in that habitat. Describe the habitat (Is it fresh or salt water? Does the water have a current? Is there sand, dirt, or plants?) and describe the different species that are there (Are they birds, fish, grass, trees, etc? Do the animals live there or are they visiting?). Have people made it easier or harder for animals to live in these habitats?"),
            ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "4TH - 5TH", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "2D MIXED MEDIA PAINTING*", subHeader: "(INDIVIDUALS & AT-HOME | UP TO 10IN X 14IN)", bodyText: "Create a 2-D drawing or painting of one of Key Biscayne’s natural resources that includes a change or impact caused by humans (pollution, development, invasive species introduction, etc.). Mixed Media may include all types of paint and dry media. Include a written description of the artwork which includes a comment about what is important or unique about the subject of the painting or drawing."),
                KeyChallengeTableRow(header: "PHOTOGRAPH*", subHeader: "(INDIVIDUALS & AT-HOME | 8IN X 10IN WITHOUT MAT)", bodyText: "Take a photograph (micro or macro) of a human impact of an aquatic or shoreline environment of Key Biscayne (i.e. trash, pollution, development, invasive species introduction, etc.). Include a title for the photograph as well as a short description of the location of the photo." + "\n\n" + "Photographs must also be uploaded to the Key Science interactive map. Go to https://www.keyscience.org/lab/record/ and click on \"Upload your photos\""),
                KeyChallengeTableRow(header: "PUBLIC SERVICE ANNOUNCEMENT", subHeader: "(INDIVIDUALS & GROUPS | VIDEO UP TO 8 MINUTES)", bodyText: "Create a PSA video which sends an environmental message for our community about the importance of proper disposal of trash and its impact on the environment. Entries will be submitted to info@keyscience.org via Dropbox."),
                KeyChallengeTableRow(header: "PERSONAL NARRATIVE", subHeader: "(INDIVIDUALS & GROUPS | VARIOUS FORMATS)", bodyText: "Create a personal narrative (fictional) with yourself as a native plant or animal, that has been affected by humans in some way, and which takes place around Key Biscayne or surrounding waters. Max 24 pages (not including the front cover)." + "\n\n" + "Alternatively, students may opt to create a retelling of an oral history interview with a \"Key Rat\" (Long-time Key Biscayne resident) about his or her favorite natural settings on Key Biscayne and how these places have changed over time due to human activity. This could be a report or a video. KBCF can aid in connecting students to long-time Key residents if needed. Can be a PPT or Prezi of 5-10 slides (with information and pictures) or a video of maximum length of 8 minutes. Entries will be submitted to info@keyscience.org via Dropbox."),
                KeyChallengeTableRow(header: "SCIENCE PROJECT*", subHeader: "(INDIVIDUALS, GROUPS, & AT-HOME | PRESENTED ON A POSTER/SCIENCE BOARD, NO LARGER THAN 36\" BY 48\" )", bodyText: "Choose a local, native habitat (reef, shoreline, freshwater, etc.) and observe and list the different plants and animals that are present in that habitat. Describe the habitat and the different species of plants and animals, including why these particular species might be present. Also describe how changes in water quality, pollution, or human development might affect these species. Present data on a poster/foam core board with pictures."),
            ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "6TH - 8TH", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "COLORING BOOK", subHeader: "(INDIVIDUALS & GROUPS | VARIOUS FORMATS)", bodyText: "Create a coloring book that tells a narrative of a native plant or animal that has been affected by humans in some way, and which takes place around Key Biscayne or surrounding waters. Keep in mind that this project is being made for a younger audience, to give older students a chance to teach younger students about the environment. Max 24 pages (not including the front cover)." + "\n\n" + "Alternatively, students may opt to create a retelling of an oral history interview with a \"Key Rat\" (Long-time Key Biscayne resident) about his or her favorite natural settings on Key Biscayne and how these places have changed over time due to human activity. This could be a report, presentation, or a video. KBCF can aid in connecting students to long-time Key residents if needed. Max 5 page report (may include a few pictures), a PPT or Prezi of 8-10 slides (with information and pictures), or a video of maximum length of 8 minutes. Entries will be submitted to info@keyscience.org via Dropbox."),
                KeyChallengeTableRow(header: "SCIENCE PROJECT*", subHeader: "(INDIVIDUALS, GROUPS, & AT-HOME | PRESENTED ON A POSTER/SCIENCE BOARD, NO LARGER THAN 36\" BY 48\" )", bodyText: "Create a poster featuring an invasive/non-native species found in South Florida (or specifically Key Biscayne). Explain how this species was introduced (in particular, how humans were directly or indirectly responsible), the impacts it has had on the environment and/or other animals species, and possible methods of control if there are any. Research information and include data where appropriate, such as population changes, dates of introduction, or anything else pertinent."),
                KeyChallengeTableRow(header: "NATURE GUIDE", subHeader: "(INDIVIDUALS & GROUPS | MAX 28 PGS INCLUDING COVER)", bodyText: "Create a nature guide for the waters of Key Biscayne which includes at least 10 native species (animals, sea grasses, corals, mangroves, etc.) and describes ways to minimize human impact."),
                KeyChallengeTableRow(header: "PHOTOGRAPH*", subHeader: "(INDIVIDUALS & AT-HOME | 8IN X 10IN WITHOUT MAT)", bodyText: "Take a photograph (micro or macro) of a human impact of an aquatic or shoreline environment of Key Biscayne (i.e. trash, pollution, development, invasive species introduction, etc.). Include a title for the photograph as well as a short description of the location of the photo." + "\n\n" + "Photographs must also be uploaded to the Key Science interactive map. Go to https://www.keyscience.org/lab/record/ and click on \"Upload your photos\""),
                KeyChallengeTableRow(header: "PUBLIC SERVICE ANNOUNCEMENT", subHeader: "(INDIVIDUALS & GROUPS | VIDEO UP TO 8 MINUTES)", bodyText: "Create a PSA video which sends an environmental message for our community about the importance of the effects of trash on the native species of Key Biscayne. Include the dangers facing our waters (pollution, development, etc.) and ways in which individuals can help to reduce these problems. Entries will be submitted to info@keyscience.org via Dropbox."),
            ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "9TH - 10TH", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "FOOD WEB*", subHeader: "(INDIVIDUALS, GROUPS, & AT-HOME | UP TO 10IN X 14IN)", bodyText: "Create a food web photo collage of an animal native to a water habitat around Key Biscayne, and write a brief description of how this food web may be affected by human activity."),
                KeyChallengeTableRow(header: "PHOTOGRAPH*", subHeader: "(INDIVIDUALS & AT-HOME | 8IN X 10IN WITHOUT MAT)", bodyText: "Take a photograph (micro or macro) of a human impact of an aquatic or shoreline environment of Key Biscayne (i.e. trash, pollution, development, invasive species introduction, etc.). Include a title for the photograph as well as a short description of the location of the photo." + "\n\n" + "Photographs must also be uploaded to the Key Science interactive map. Go to https://www.keyscience.org/lab/record/ and click on \"Upload your photos\""),
                KeyChallengeTableRow(header: "COLORING BOOK OR ILLUSTRATED STORY", subHeader: "(INDIVIDUALS & GROUPS | MAX 28 PGS INCLUDING COVER)", bodyText: "Create a story that tells a narrative of a native plant or animal that has been affected by humans in some way, and which takes place around Key Biscayne or surrounding waters. Keep in mind that this project is being made for a younger audience, to give older students a chance to teach younger students about the environment."),
                KeyChallengeTableRow(header: "PUBLIC SERVICE ANNOUNCEMENT", subHeader: "(INDIVIDUALS & GROUPS | VIDEO UP TO 8 MINUTES)", bodyText: "Create a PSA video which sends an environmental message for our community about the importance of the effects of trash on the native species of Key Biscayne. Include the dangers facing our waters (pollution, development, etc.) and ways in which individuals can help to reduce these problems. Entries will be submitted to info@keyscience.org via Dropbox."),
                KeyChallengeTableRow(header: "SCIENCE REPORT*", subHeader: "(INDIVIDUALS & AT-HOME | POWERPOINT, PREZI , OR REPORT)", bodyText: "Create a PPT, Prezi, or report which describes the consequences of human activity on waters of Key Biscayne. This should include data collection and analysis; the level of detail will be left up to participants, but more detailed information will likely score higher. Max 7 page report (may include a few pictures), a PPT, or Prezi (maximum 25 slides). Entries will be submitted to info@keyscience.org via Dropbox."),
                ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "11TH - 12TH", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "SCIENCE REPORT*", subHeader: "(INDIVIDUALS & AT-HOME | 8-10 PAGES)", bodyText:
                    "Write a report detailing a specific or general aspect of human quality impact around the local environments of Key Biscayne."
                    + "\n\n" +
                    "The report can be broad (for example, the overall effects of human development on the shores of Key Biscayne), or more detailed (for example, how plastic pollution affects one specific species of aquatic organism). It can include any aspect of human impacts: pollution, trash, agricultural runoff, introduction of invasive/non-native species, land development, etc."
                    + "\n\n" +
                    "The subject and detail-level of the report will be left to the participant to decide, however all reports should show research, data collection, and analysis. It should loosely follow the scientific method: 1) ask a question, 2) do background research, 3) construct a hypothesis, 4) collect data and/or test hypothesis, 5) review accuracy of hypothesis, and 6) draw a conclusion."
                    + "\n\n" +
                    "Students can either create their own experiment based on their hypothesis and collect data that they will include in their report, or they can write a research paper using data sources from other scientific literature to prove or disprove their hypothesis. All outside sources must be cited." + "\n\n" + "As this is a more involved and detailed project, it will include a monetary award of $200 for 1st place, $150 for 2nd place, and $100 for 3rd place."),
            ]),
            
            KeyChallengeTableSection(header: CollapsibleTableHeader(title: "AT-HOME", arrow: "down-arrow"), rows: [
                KeyChallengeTableRow(header: "AT-HOME PROJECTS", subHeader: "(CHOOSE ONLY ONE PROJECT PER STUDENT)", bodyText:
                    "Students who live on Key Biscayne but do not attend school on the Key or who attend school on the Key but whose class is not participating may still participate in the Key Challenge, following these guidelines:"
                        + "\n\n" +
                        "• Each student registrant may enter with one of the challenges given for their grade level category. The challenges listed on previous pages which will be allowed for the At-Home entries are marked with an asterisk (*)."
                        + "\n" +
                        "• The student registrant’s parent/guardian may register him or her online in the At-Home category, or the student may register him or herself if old enough to do so (high school age)."
                        + "\n" +
                        "• The student registrant will need to have their current teacher fill out and sign a form affirming their current grade level. The form will be available for download on the online registration page."
                        + "\n" +
                        "• Each At-Home challenge entry will only be judged against other At-Home entries of the same grade level category."
                        + "\n" +
                        "• Parents may provide guidance, but should allow the student to do the challenge on their own as much as possible."),
            ]),
            
        ]
        
        return tableSections
    }
}
